DROP TABLE IF EXISTS GameStore.GameStoreInfo
DROP TABLE IF EXISTS GameStore.GamePlatform
DROP TABLE IF EXISTS GameStore.Employees
DROP TABLE IF EXISTS GameStore.OrderLines
DROP TABLE IF EXISTS GameStore.Orders
DROP TABLE IF EXISTS GameStore.Customers
DROP TABLE IF EXISTS GameStore.Games
DROP TABLE IF EXISTS GameStore.Genres
DROP TABLE IF EXISTS GameStore.Platforms
DROP TABLE IF EXISTS GameStore.Hours
DROP TABLE IF EXISTS GameStore.Stores
DROP TABLE IF EXISTS GameStore.Conditions
